In [1]:
from numpy import array
from numpy.linalg import eig\

import numpy as np
A = np.random.randint(1,10,size = (3,3))

print(A)

[[7 2 3]
 [3 6 8]
 [1 7 5]]


In [3]:
values ,vectors = eig(A)
print(values)

[14.33541428  5.55930931 -1.89472359]


In [5]:
print(vectors)

[[-0.42513785 -0.92719401 -0.08566026]
 [-0.70171605  0.15953561 -0.69291175]
 [-0.57171006  0.33890952  0.71591594]]


In [7]:
B = np.random.randint(1,10,size = (3,3))
values,vectors = eig(B)


In [9]:
values

array([14.09490352, -2.81595239,  2.72104887])

In [11]:
vectors

array([[-0.86033358, -0.75577844, -0.11889377],
       [-0.41446038,  0.60788435, -0.62747706],
       [-0.29673004,  0.24346575,  0.76950427]])

In [13]:
C = B.dot(vectors[:, 0]) # Matrix multiply by fist column of eigenvector
print(C)

[-12.12631885  -5.8417791   -4.18238129]


In [15]:
D = vectors[:, 0]*values[0]  # eigenvector multiply by eigenvalues
print(D)

[-12.12631885  -5.8417791   -4.18238129]


In [23]:
# recunstrcutiing matrix
import numpy as np

A = np.random.randint(1,10,size=(3,3))
values,vectors = np.linalg.eig(A)
print(A)
Q = vectors
# create inverse matrix
R = np.linalg.inv(Q)
# makeing eigenvalues to diagonal matrix 
L = np.diag(values)
#reconstruct

B = Q.dot(L).dot(R)

[[9 4 3]
 [8 5 8]
 [3 2 8]]


In [25]:
print(B)

[[9. 4. 3.]
 [8. 5. 8.]
 [3. 2. 8.]]
