## Factorization 
---

### Matrix Decomposition (Matrix factirization methods)

Many Complex Matrix problems Are Not Solved efficently or with stability 
using the limited  precison of computers. So Matrix Decomposition are the method 
Which Reduce The matrix into constituent parts that make it easier to calculate

---
### What is matrix Decomposition
 This is a Way of reducing a matrix into its contituent parts , it is an approach 
 which can simplify more complex problems 

 - Ex :-  
     A common analogy of matrix decomposition is factoring of number such as 
     factoring of 10 = 2x5

---
### LU decomposition
many way to decompose a matrix , hence there are a range of diffrent matrix decomposition
technique. Two simple and widely used matrix decomposition methods are the Lu Matrix
And QR matrix decomposition

---

## Lu decomposition

This matrix is for Square matrix and it decomposes a matrix into **L and U components**

---
-   ### A = L.U
-   **Here A is Square matrix Which we Wish to decompose**
-   **L is Lower Triangular Matrix**
-   **U is Upper Triangular Matrix**

- > The LU decomposition is found using an iterative numerical process and can fail foor those
  > matrix that cannot decompose easily . Than comes LUP(Lu decomposition With Partial Pivotiing)
  > -  **This is more stable**
  > -  **A = L.U.P**

---
## QR Decomposition
The decomposition for (n x m) matrix  and decomposess a matrix into Q and r components 

- ### A =  Q . R
- **Where A is matrix We Want to decompose**
- **Q is M xm matrix**
- **R is Upper Triangular Matrix**

----
## Cholesky decomposition

This decomposition Is for Symmetric Square matrix Where All Values Are greater than zero, so called positive definite matrices.

- ### > A = L . L^T
-  **L is Lower Triangular Matrix  And L^t is Transpose Of L**
-  **This is Also Written In A = U . U^T**

In [31]:
import numpy as np 
from scipy.linalg import lu
A = np.random.randint(1,10,size = [3,3])
print(A)

[[9 1 6]
 [1 5 9]
 [9 5 6]]


In [33]:
P,L,U = lu(A)
print("Pivot : \n",P)
print("\nLower Triangular: \n",L)
print("\nUpper Triangular: \n",U)


Pivot : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Lower Triangular: 
 [[1.         0.         0.        ]
 [0.11111111 1.         0.        ]
 [1.         0.81818182 1.        ]]

Upper Triangular: 
 [[ 9.          1.          6.        ]
 [ 0.          4.88888889  8.33333333]
 [ 0.          0.         -6.81818182]]


In [39]:
LPU =P.dot(L).dot(U)
print(LPU)

[[9. 1. 6.]
 [1. 5. 9.]
 [9. 5. 6.]]


# QR Decomposition

In [35]:
from numpy.linalg import qr

Q,R = qr(A,'complete')
print(Q)
print("\n",R)

[[-0.7049344   0.41465848 -0.57543534]
 [-0.07832604 -0.85185275 -0.5178918 ]
 [-0.7049344  -0.32000818  0.63297887]]

 [[-12.76714533  -4.62123665  -9.16414726]
 [  0.          -5.44464616  -7.09877293]
 [  0.           0.          -4.31576503]]


In [ ]:
B = Q.dot(R)
print(B)

# Cholesky decomposition

In [65]:
from numpy.linalg import cholesky
A = np.array([
     [2,1,1],
     [1,2,1],
     [1,1,2]])
print(A)
#factorize
L = cholesky(A)
print(L)
#reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
