In [3]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([3,2,5,6])
print(a.dot(b))
print("Sum = ",a+b)
print("Substract = ",a-b)


46
Sum =  [ 4  4  8 10]
Substract =  [-2  0 -2 -2]


In [5]:
a = np.random.randint(1,10,size = (3,3,3))
print(a)
print("Dimesnion Of A Is ",np.ndim(a))
print("Shape Of A is ",np.shape(a))

[[[9 3 8]
  [5 6 7]
  [4 5 2]]

 [[9 3 1]
  [9 7 3]
  [7 2 3]]

 [[4 1 8]
  [5 9 7]
  [8 6 2]]]
Dimesnion Of A Is  3
Shape Of A is  (3, 3, 3)


In [11]:
print("Zero Matrix",np.zeros(5))
print("One Matrix \n",np.ones((3,3)))
print("identity Matrix \n",np.eye(4,4))

Zero Matrix [0. 0. 0. 0. 0.]
One Matrix 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
identity Matrix 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
a = [2, 4, 6]
b = [1, 3, 5]

scalar = 3
print("using Numpy",scalar *np.array(a))
for i in range(len(a)):
    a[i] = scalar * a[i]
print(a)



using Numpy [ 6 12 18]
[6, 12, 18]


In [ ]:
v = [3, 4]
print("maginitude of vecator = ",np.sqrt(v[0] **2 +v[1]**2))



maginitude of vecator =  5.0


In [19]:
#Write a program to compute the angle between two vectors using dot product formula.
a = np.random.randint(1,5,size=(5))
b = np.random.randint(1,5,size=(5))

cos_theta = (a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b)))
print(cos_theta)
print("theta = ",np.cos(cos_theta))


0.8237544710479141
theta =  0.6794713395797468


In [31]:
# Transpose Of MAtrix
a = np.random.randint(1,10,size = (3,3))
print("Orignal A Matrix = \n",a)
print("Transpose Of A Matrix = \n",a.T)

# Cheak Matrix Is Symetric 
if a is a.T:
    print("Symetric Matrix")
else:
    print(" Not Symmetric Matrix")


# Multiply with another matrix
print("Multiply = \n",a.dot(np.random.randint(1,5,size=(3,3))))

# Find Inverse Of MAtrix
print("Inverse Of A is = \n",np.linalg.inv(a))

# Verify AxA^-1 = I
prod = np.matmul(a,np.linalg.inv(a))

if prod is np.eye(3,3):
    print("yes")
else:
    print("No")

Orignal A Matrix = 
 [[4 5 1]
 [6 9 9]
 [1 6 9]]
Transpose Of A Matrix = 
 [[4 6 1]
 [5 9 6]
 [1 9 9]]
 Not Symmetric Matrix
Multiply = 
 [[19 22 24]
 [39 42 60]
 [23 19 37]]
Inverse Of A is = 
 [[-0.3         0.43333333 -0.4       ]
 [ 0.5        -0.38888889  0.33333333]
 [-0.3         0.21111111 -0.06666667]]
No


In [40]:


A = np.array([[2,1],
              [1,2]])

# Get eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Check for each eigenvector
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]   # ith eigenvector
    lambda_ = eigenvalues[i]

    Av = A @ v
    lv = lambda_ * v

    print(f"\nEigenvalue: {lambda_}")
    print("Av =", Av)
    print("λv =", lv)


Eigenvalue: 3.0
Av = [2.12132034 2.12132034]
λv = [2.12132034 2.12132034]

Eigenvalue: 1.0
Av = [-0.70710678  0.70710678]
λv = [-0.70710678  0.70710678]




🔹 Section 7: SVD (Important for ML)
Q20

Perform Singular Value Decomposition:

A = [[1,2],
     [3,4],
     [5,6]]
Q21

Reconstruct matrix using:
👉 U · Σ · Vᵀ

🔥 Bonus (ML-Oriented Questions)
Q22

Given:

X = [[1,2],
     [3,4],
     [5,6]]

w = [0.5, 1.5]

👉 Compute:

y = X · w
Q23

Normalize a vector (make its magnitude = 1)

Q24

Write a program to:

Compute cosine similarity between two vectors
Q25

Create a random 3×3 matrix and:

Compute determinant
Check if invertible
💥 Challenge Set (Hard)
Q26

Implement matrix multiplication without NumPy

Q27

Implement dot product without NumPy

Q28

Write your own function to compute transpose

Q29

Write your own function to compute determinant of 2×2 matrix

Q30

Build a mini linear regression prediction using:
👉 y = Xw

In [ ]:
import numpy as np

a = np.array([2, 7])
b = np.array([7, 2])

diff = b - a                         # difference vector [-5, 5] wait no → [5, -5]
print("Difference vector:", diff)    # [5 -5]

# L1 by hand
l1_manual = np.sum(np.abs(diff))
print("L1 (manual):", l1_manual)     # |5| + |-5| = 10

# L1 using NumPy  L1 Is Manhhatan
l1_numpy = np.linalg.norm(diff, ord=1)
print("L1 (numpy): ", l1_numpy)      # 10.0


# L2 is Euclidian Distance 
# L2 by hand — square each difference, sum, take sqrt
l2_manual = np.sqrt(np.sum(diff**2))
print("L2 (manual):", round(l2_manual, 4))   # sqrt(25 + 25) = 7.0711

# L2 using NumPy (default when no ord given)
l2_numpy = np.linalg.norm(diff)
print("L2 (numpy): ", round(l2_numpy, 4))    # 7.0711

# Also available directly
l2_scipy = np.sqrt((diff**2).sum())
print("L2 (sqrt sum squares):", round(l2_scipy, 4))   # 7.0711